### ISSUE TITLE
QA - When will I see the CLI command?

### ISSUE THREAD

**Issue by shiraez** [stepanblyschak/sonic-example-extension#1]
I have a QA regarding the sonic extension.
Will the CLI command be seen if the container will run?
or does it depend on whether we compile the sonic image with the docker?

**Comment by stepanblyschak** [comment]
Once you have installed extension via ```sonic-package-manager``` command or by integrating extension into the build - the CLI command will become available. E.g, when extension is installed but not enabled (container is down) the CLI provided by extension is still available.

**Comment by shiraez** [comment]
If I don't install the ```sonic-package-manager``` command and add the docker similar to the docker-dhcp-relay docker(in sonic buildimage repo), will the CLI command still be enabled only if the container is up?
